baseurl = "https://dl.dropboxusercontent.com/u/11077613/"
languageCode = "en-us"
title = "Castillo Sings"
buildFuture = true
theme = "hugo-creative-theme"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more informtion take a look at the README.

  # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
  name = "Adrian Castillo"
  description = "This is a site about Adrian Castillo Jazz singer, singing teacher, electronic musician. New jazz dates in Berlin Germany will be posted regularly"


  # Navigation
  [params.navigation]
    brand = "Castillo sings"

    [params.navigation.links]
      about     = "About"
      services  = "Singing Lessons"
      portfolio = "Main Projects"
      contact   = "Contact"


  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "Welcome"
    subtitle   = "This is where you will find all the information about me as a jazz singer and as a singing teacher. I will also post all upcoming concert dates. Thank you for being here."
    buttonText = "More information"


  # About section
  [params.about]
    headline    = "About me."
    description = "I am a jazz singer living in Berlin since August 2012. I studied music at the Bern University of the Arts with jazz singing as main instrument under the guidance of two wonderful ladies of Jazz: Sandy Patton and Efrat Alony. As second instrument I had the priviledge to practice classical singing with the cantatrice Denise Bregnard. I am currently performing with a few bands in Berlin. I would love to see you at the next gig!"
    buttonText  = "Upcoming Concerts"


  # Service section
  [params.services]
    headline = "Everybody can sing."

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Find your voice."
            description = "With just a little help you can unearth your voice and make it shine."
            
        [[params.services.list]]
            icon = "fa-leanpub"
            title = "Choose what to work on."
            description = "Classical technique or Jazz improv, voice placement or your own material: you choose what we work on. Connect with your body through physical alignment, breathing and relaxation techniques."

        [[params.services.list]]
      icon = "fa-subway"
      title = "I will travel."
      description = "If you feel more comfortable learning at your own home, it will only cost you an additional € 5.- transport fee."

    

        [[params.services.list]]
            icon = "fa-heart"
            title = "You love music."
            description = "As a time goes by one might lose sight of what we really love. Find your way back!"


    # Portfolio modals
  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"
    
     # Concert Dates
  [params.concerts]
        client = "Location"
        date = "Date"
        category = "Genre"
        buttonText = "Close"

    # Aside section
  [params.aside]
    headline = "The room"

  [params.aside.button]
      text = "See the prices!"
      link = "#"

  # Contact section
  [params.contact]
    headline = "Let's get in touch!"
    description = "You want to book some of us? Or you decided that it is time to do something for your voice? That's great! Give me a call or send me an email and I will get back to you as soon as possible!"
    phone = "+49-172-9315121"
    email = "jazzvocalistme@gmail.com"
